name: showoff
description: :plotsklapps showing off

version: 0.0.2+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flex_color_scheme: ^4.1.1
  google_fonts: ^2.1.0
  flutter_spinkit: ^5.1.0
  flip_card: ^0.6.0
  animated_text_kit: ^4.2.1
  font_awesome_flutter: ^9.2.0
  url_launcher: ^6.0.15
  flutter_email_sender: ^5.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/certificates/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/plotsklappsiconblack.png"

flutter_native_splash:

  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove

  color: "#ffffff"
  image: assets/icons/plotsklappsiconwhite400x400.png
  color_dark: "#000000"
  image_dark: assets/icons/plotsklappsiconblack400x400.png

  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  #android: false
  #ios: false
  #web: false

  android_gravity: center
  ios_content_mode: center
  web_image_mode: center

  fullscreen: true
