name: showoff
description: :plotsklapps showing off

version: 0.0.6+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flex_color_scheme: ^6.0.0
  google_fonts: ^3.0.1
  flutter_spinkit: ^5.1.0
  flip_card: ^0.6.0
  animated_text_kit: ^4.2.1
  font_awesome_flutter: ^10.1.0
  url_launcher: ^6.0.15
  flutter_email_sender: ^5.0.2
  carousel_slider: ^4.0.0
  audioplayers: ^1.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.8
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/sounds/
    - assets/images/certificates/
    - assets/images/dice/
    - assets/images/screenshots/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/plotsklappsIcon.png"

flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove
  color: "#dedede"
  image: assets/icons/plotsklappsLogoStacked.png
  color_dark: "#dedede"
  image_dark: assets/icons/plotsklappsLogoStacked.png
  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  #android: false
  #ios: false
  #web: false
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center

  fullscreen: true
