// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZuUwZDf9GTnHPthf1OfTzj3qrnADGYiU',
    appId: '1:961435789802:web:b700a065a54a4e0a5eaa93',
    messagingSenderId: '961435789802',
    projectId: 'showoff-plotsklapps',
    authDomain: 'showoff-plotsklapps.firebaseapp.com',
    storageBucket: 'showoff-plotsklapps.appspot.com',
    measurementId: 'G-XKQ6NE0BPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRaooSOXORAA2TNF-r0FQBFDgU3lOnMJs',
    appId: '1:961435789802:android:136bcccafc76ee5f5eaa93',
    messagingSenderId: '961435789802',
    projectId: 'showoff-plotsklapps',
    storageBucket: 'showoff-plotsklapps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQpP_6FY4xcnOFyBZozVpfm0MLBzLFwPI',
    appId: '1:961435789802:ios:929a5592adb12aa95eaa93',
    messagingSenderId: '961435789802',
    projectId: 'showoff-plotsklapps',
    storageBucket: 'showoff-plotsklapps.appspot.com',
    iosClientId: '961435789802-sugglnctejahasiu1h0m1fptj5v8vjpr.apps.googleusercontent.com',
    iosBundleId: 'nl.plotsklapps.showoff',
  );
}
